config/routes.rb
Rails.application.routes.draw do

  get 'index', to:'tasks#index'

  get 'tasks/new', to:'tasks#new', as: 'new'

  post 'tasks', to:'tasks#create', as: 'tasks'

  get 'tasks/:id', to:'tasks#show', as: 'task'

  get 'tasks/:id/edit', to:'tasks#edit', as:'edit'

  patch 'tasks/:id', to:'tasks#update', as: 'update'

  delete 'tasks/:id', to:'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    #@tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
   #@tasks = Task.find(params[:id])
  end

  def destroy
    #@tasks = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def update
    #@tasks = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end
end

private
def task_params
  params.require(:task).permit(:title, :details, :completed)
end

def set_task
    @task = Task.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task, :as => :task, :url => update_path) do |t|%>

  <%= t.label :title %>
  <%= t.text_field :title %>


  <%= t.label :details %>
  <%= t.text_field :details  %>
  </div>

  <%= t.check_box :completed %>

  <%= t.submit %>

<% end %>

app/views/tasks/index.html.erb
<h1> List of tasks</h1>
<ul>
<% @tasks.each do |task| %>
  <li>
  <h2><%= link_to task.title, task_path(task) %></h2>
  </li>
    <li>
  <p><%= task.details %></p>
  </li>
  <li>
  <p> Task completed?  <%= task.completed %></p>
  </li>
<% end %>
</ul>

<p> <%= link_to "Add new task", new_path %></p>

app/views/tasks/new.html.erb
<%= form_for(@task, :as => :task, :url => tasks_path) do |t| %>

  <%= t.label :title %>
  <%= t.text_field :title %>


  <%= t.label :details %>
  <%= t.text_field :details  %>

  <%= t.check_box :completed %>

  <%= t.submit %>

<% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %></h1>
<ul>

    <li>
  <h3><%= @task.details %></h3>
    <%= link_to "Delete task", destroy_path(@task),
    method: :delete %>
  </li>

<li>
  <p> Task completed?  <%= @task.completed %></p>
  </li>

</ul>

<p> <%= link_to "Update task", edit_path %></p>

<p> <%= link_to "Back to list", index_path %></p>